### ISSUE TITLE
tsconfig.json

### ISSUE THREAD

**Issue by Sodininkas** [johnligt/Knockout-TypeScript-Webpack-Starter#1]
tsconfig.json is not included

**Comment by JasonColeyNZ** [comment]
Did you get an answer or fix for this, or is this because of a newer version of ts, i am new to ts, so not sure where to go from here

**Comment by johnligt** [comment]
Hello Jason,
I added the file to the repo today.

**Comment by JasonColeyNZ** [comment]
Cheers!
