### ISSUE TITLE
Getting lots of Knockout issues after running Webpack

### ISSUE THREAD

**Issue by sachabarber** [johnligt/Knockout-TypeScript-Webpack-Starter#2]
ERROR in C:\Users\sacha\Downloads\Knockout-TypeScript-Webpack-Starter-master\Web\typings\globals\knockout\index.d.ts
(16,2): error TS2411: Property 'equalityComparer' of type '(a: any, b: any) => boolean' is not assignable to string index type 'KnockoutBindingHandler'.

ERROR in C:\Users\sacha\Downloads\Knockout-TypeScript-Webpack-Starter-master\Web\typings\globals\knockout\index.d.ts
(60,5): error TS2411: Property 'subscribe' of type '{ (callback: (newValue: T) => void, target: any, event: "beforeChange"): KnockoutSubscription; (c...' is not assignable to string index type 'KnockoutBindingHandler'.

ERROR in C:\Users\sacha\Downloads\Knockout-TypeScript-Webpack-Starter-master\Web\typings\globals\knockout\index.d.ts
(64,2): error TS2411: Property 'extend' of type '(requestedExtenders: { [key: string]: any; }) => KnockoutSubscribable<T>' is not assignable to string index type 'KnockoutBindingHandler'.

ERROR in C:\Users\sacha\Downloads\Knockout-TypeScript-Webpack-Starter-master\Web\typings\globals\knockout\index.d.ts
(65,2): error TS2411: Property 'getSubscriptionsCount' of type '() => number' is not assignable to string index type 'KnockoutBindingHandler'.

ERROR in C:\Users\sacha\Downloads\Knockout-TypeScript-Webpack-Starter-master\Web\typings\globals\knockout\index.d.ts
(79,2): error TS2411: Property 'dispose' of type '() => void' is not assignable to string index type 'KnockoutBindingHandler'.

ERROR in C:\Users\sacha\Downloads\Knockout-TypeScript-Webpack-Starter-master\Web\typings\globals\knockout\index.d.ts
(80,2): error TS2411: Property 'isActive' of type '() => boolean' is not assignable to string index type 'KnockoutBindingHandler'.

ERROR in C:\Users\sacha\Downloads\Knockout-TypeScript-Webpack-Starter-master\Web\typings\globals\knockout\index.d.ts
(81,2): error TS2411: Property 'getDependenciesCount' of type '() => number' is not assignable to string index type 'KnockoutBindingHandler'.

ERROR in C:\Users\sacha\Downloads\Knockout-TypeScript-Webpack-Starter-master\Web\typings\globals\knockout\index.d.ts
(82,5): error TS2411: Property 'extend' of type '(requestedExtenders: { [key: string]: any; }) => KnockoutComputed<T>' is not assignable to string index type 'KnockoutBindingHandler'.

ERROR in C:\Users\sacha\Downloads\Knockout-TypeScript-Webpack-Starter-master\Web\typings\globals\knockout\index.d.ts
(92,5): error TS2411: Property 'subscribe' of type '{ (callback: (newValue: KnockoutArrayChange<T>[]) => void, target: any, event: "arrayChange"): Kn...' is not assignable to string index type 'KnockoutBindingHandler'.

ERROR in C:\Users\sacha\Downloads\Knockout-TypeScript-Webpack-Starter-master\Web\typings\globals\knockout\index.d.ts
(97,5): error TS2411: Property 'extend' of type '(requestedExtenders: { [key: string]: any; }) => KnockoutObservableArray<T>' is not assignable to string index type 'KnockoutBindingHandler'.

ERROR in C:\Users\sacha\Downloads\Knockout-TypeScript-Webpack-Starter-master\Web\typings\globals\knockout\index.d.ts
(110,2): error TS2411: Property 'peek' of type '() => T' is not assignable to string index type 'KnockoutBindingHandler'.

ERROR in C:\Users\sacha\Downloads\Knockout-TypeScript-Webpack-Starter-master\Web\typings\globals\knockout\index.d.ts
(111,2): error TS2411: Property 'valueHasMutated' of type '() => void' is not assignable to string index type 'KnockoutBindingHandler'.

ERROR in C:\Users\sacha\Downloads\Knockout-TypeScript-Webpack-Starter-master\Web\typings\globals\knockout\index.d.ts
(112,2): error TS2411: Property 'valueWillMutate' of type '() => void' is not assignable to string index type 'KnockoutBindingHandler'.

ERROR in C:\Users\sacha\Downloads\Knockout-TypeScript-Webpack-Starter-master\Web\typings\globals\knockout\index.d.ts
(113,5): error TS2411: Property 'extend' of type '(requestedExtenders: { [key: string]: any; }) => KnockoutObservable<T>' is not assignable to string index type 'KnockoutBindingHandler'.

**Comment by johnligt** [comment]
This caused because of the use of TypeScript version which is too high. This project uses TypeScript 2.0, which is not available by default in Visual Studio 2017. To make this TypeScript version available in Visual Studio 2017 go to Tools > Get Tools and Features. The choose "Individual components". Scroll down to "SDK's, libraries and frameworks", and check "TypeScript 2.0 SDK", and click on the "Modify" button, at the bottom right corner of the window.

I have now also fixed the TypeScript version to 2.0.10 in package,json (in stead of compatible with 2.0.3), to get this change please pull again.

When you load the project the first time in Visual Studio 2017, when the message appears asking if you want to upgrade the project to TypeScript 2.3 you need to choose "No".
